# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjYzbpQOmYa5_qMctzOihWXjI0PohOQ0
"""

from crewai import Agent
from langchain.agents import load_tools
from langchain_groq import ChatGroq

tools = load_tools(["human"])

GROQ_LLM = ChatGroq(
            api_key=os.getenv("GROQ_API_KEY"),
            model="llama3-8b-8192"
        )

class Agents():
    def research_agent(self):
        return Agent(
            role='Research Analyst',
            goal='Analyze the initial provided information to extract insights on relevant content to the given initial job information focusing on Job Title, Job Scope, Responsibilities and Requirement',
            backstory='Expert in analyzing the nuances of jobs and identifying key values and needs for a given job position.',
            llm = GROQ_LLM,
            verbose=True
        )

    def question_agent(self):
        return Agent(
            role='Question Expert',
            goal='Use insights from the Research Analyst to create a list of comprehensive follow up questions to extract further details from hiring manager',
            tools= tools,
            backstory='Skilled in crafting good follow up questions that helps extracting informations.',
            llm = GROQ_LLM,
            verbose=True
        )

    def writer_agent(self):
        return Agent(
            role='Review and Editing Specialist',
            goal='Review the job posting for clarity, accuracy, format appropriation and send to hiring manager to finalize',
            backstory='A meticulous editor with an eye for detail, ensuring every piece of content is clear, concise, and follows the requested format properly.',
            llm = GROQ_LLM,
            verbose=True
        )

    def review_agent(self):  # Corrected the indentation here
        return Agent(
            role='Review and Editing Specialist',
            goal='Review the job posting for clarity, engagement, grammatical accuracy, and alignment with company values and refine it to ensure perfection.',
            backstory='A meticulous editor with an eye for detail, ensuring every piece of content is clear, engaging, and grammatically perfect.',
            llm = GROQ_LLM,
            verbose=True
        )