# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjYzbpQOmYa5_qMctzOihWXjI0PohOQ0
"""

import os
from crewai import Crew
from agents import Agents
from tasks import Tasks

os.environ["GROQ_API_KEY"] = "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"


tasks = Tasks()
agents = Agents()

print("Welcome to Job Description Generator\n")
hiring_needs = input("What are you trying to hire?\n")


# Create Agents
researcher_agent = agents.research_agent()
questioner_agent = agents.question_agent()
writer_agent = agents.writer_agent()
review_agent = agents.review_agent()

# Define Tasks for each agent
research_role_task = tasks.research_role_task(researcher_agent, hiring_needs)
questioner_task = tasks.questioner_task(questioner_agent, hiring_needs)
draft_job_posting_task = tasks.draft_job_posting_task(writer_agent, hiring_needs)
review_and_edit_job_posting_task = tasks.review_and_edit_job_posting_task(review_agent, hiring_needs)

# Instantiate the crew with a sequential process
crew = Crew(
    agents=[researcher_agent,questioner_agent, writer_agent, review_agent],
    tasks=[
        research_role_task,
        questioner_task,
        draft_job_posting_task,
        review_and_edit_job_posting_task
    ]
)

# Kick off the process
result = crew.kickoff()

print("Job Posting Creation Process Completed.")
print("Final Job Posting:")
print(result)

# Kick off the process
result = crew.kickoff()

print("Job Posting Creation Process Completed.")
print("Final Job Posting:")
print(result)

