# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjYzbpQOmYa5_qMctzOihWXjI0PohOQ0
"""

from textwrap import dedent
from crewai import Task

class Tasks():
		def research_role_task(self, agent, hiring_needs):
					return Task(
						description=dedent(f"""\
								Based on hiring manager needs :"{hiring_needs}", Conduct comprehensive analysis using the job information obtained from users which is {hiring_needs}. Focus on understanding the job title, job scope, responsibilities \
                and requirement for given job position. Identify all correlated job content starting from most correlated one based on information \
                provided and how hiring manager provided information can be go further into detail
								Compile a report outlining correlated job content separately from possible information provided by hiring manager that can go further into detail"""),
						expected_output=dedent("""\
								A comprehensive report detailing correlated job content from hiring manager input, possible information provided by human users that can go further into details"""),
						agent=agent,
				)

		def questioner_task(self, agent, hiring_needs):
				return Task(
						description=dedent(f"""\
								Taking the report which has already outlined the correlated job content separated from information from hiring manager that requires further details, \
                generate follow up questions to users to verify whether the correlated job content is what hiring manager wanted, and extract further details for information \
                requiring further details. Take the feedback from users and compile it into a report. """),
						expected_output=dedent("""\
								A report consisting of questions and feedback from users"""),
						agent=agent,
				)

		def draft_job_posting_task(self, agent, hiring_needs):
				return Task(
						description=dedent(f"""\
                Draft a job posting for the role described by the hiring manager using all information obtained from questioner. Draft the job description such that it consists of topic Job Title, Job Scope, Responsibilities and Requirement. \
                The job description should have clear, concise and accessible content with all content under these topics written using list of bullet points."""),
            expected_output=dedent("""\
								A clear, concise job description strictly following the required format."""),
						agent=agent
				)

		def review_and_edit_job_posting_task(self, agent, hiring_needs):
				return Task(
						description=dedent(f"""\
                Provide the drafted job description to human users for finalization. Edit the drafted job description according to users request \
                Provide feedback for any necessary revisions."""),
						expected_output=dedent("""\
								A detailed job description which human users are satisfied with."""),
						agent=agent
				)